// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/service.proto

#include "proto/service.pb.h"
#include "proto/service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* ProcessingService_method_names[] = {
  "/ProcessingService/computeSum",
};

std::unique_ptr< ProcessingService::Stub> ProcessingService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ProcessingService::Stub> stub(new ProcessingService::Stub(channel, options));
  return stub;
}

ProcessingService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_computeSum_(ProcessingService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ProcessingService::Stub::computeSum(::grpc::ClientContext* context, const ::Point& request, ::Numeric* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Point, ::Numeric, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_computeSum_, context, request, response);
}

void ProcessingService::Stub::async::computeSum(::grpc::ClientContext* context, const ::Point* request, ::Numeric* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Point, ::Numeric, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_computeSum_, context, request, response, std::move(f));
}

void ProcessingService::Stub::async::computeSum(::grpc::ClientContext* context, const ::Point* request, ::Numeric* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_computeSum_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Numeric>* ProcessingService::Stub::PrepareAsynccomputeSumRaw(::grpc::ClientContext* context, const ::Point& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Numeric, ::Point, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_computeSum_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Numeric>* ProcessingService::Stub::AsynccomputeSumRaw(::grpc::ClientContext* context, const ::Point& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccomputeSumRaw(context, request, cq);
  result->StartCall();
  return result;
}

ProcessingService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ProcessingService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ProcessingService::Service, ::Point, ::Numeric, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ProcessingService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Point* req,
             ::Numeric* resp) {
               return service->computeSum(ctx, req, resp);
             }, this)));
}

ProcessingService::Service::~Service() {
}

::grpc::Status ProcessingService::Service::computeSum(::grpc::ServerContext* context, const ::Point* request, ::Numeric* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


